-- Add users with salted password hashes
CALL sp_add_user('tom', 'J@mjello', 'Tom', 'Morello', 'tmorello@hotmail.com');
CALL sp_add_user('iamsteve', 'r0ckCryst@l', 'Steve', 'Vai',
                 'stevei@protonmail.com');
CALL sp_add_user('kelsey43', 'password', 'Kelsey', 'Key', 'kel@gmail.com');
CALL sp_add_user('shrek', 'swamp123', 'Shrek', '', 'theshrek@yahoo.com');
CALL sp_add_user('1337hackerman', 'password', 'Hackerman from KungFury', '',
                 '1337hax0r@protonmail.ch');

INSERT INTO products(pid, product_name, product_img_path, product_img_alt, price, category, description)
VALUES
    (1, 'KBDPad Mark II Keyboard Kit', 
     'product_imgs/kbdpadmark2_keyboard_kit.webp', 
     'Photo of 5 Different-Colored Keypads on a Light Blue Background',
     20.00, 'kits', 'Keypad Keybaord Kit from KBDFans'),
    (2, 'Odin R3 Full Keyboard in Blue', 
     'product_imgs/odinR3_full_blue.webp', 
     'Photo of Half of Keyboard (Dark Blue Keyboard Case with Red, Black, and Blue Keycaps)',
     124.99, 'full', 'Full Keyboard Kit from KBDFans'),
    (3, 'Odin R3 Full Keyboard in White', 
     'product_imgs/odinR3_full_white.webp',
     'Photo of Half of Keyboard (White Keyboard Case with Blue-Gray, Gray, and White Keycaps)',
     124.99, 'full', 'Full Keyboard Kit from KBDFans'),
    (4, 'PBTFans Bog Keycaps', 
     'product_imgs/pbtfans_bog_keycaps.webp', 
     'Photo of Set of Dark-Grey Keycaps with Black Lettering',
     44.99, 'keycaps', 'Keycaps from KBDFans'),
    (5, 'PBTFans Cookies and Cream Keycaps',
     'product_imgs/pbtfans_cookies_and_cream_keycaps.webp', 
     'Photo of Set of White Keycaps with Black Lettering, Return and Escape Keys are Black with White Lettering',
     44.99, 'keycaps', 'Keycaps from KBDFans'),
    (6, 'PBTFans Frontier Keycaps', 
     'product_imgs/pbtfans_frontier_keycaps.webp', 
     'Photo of Set of Space-Themed, Dark-Grey Keycaps with Yellow, Blue, and Red Lettering',
     44.99, 'keycaps', 'Keycaps from KBDFans'),
    (7, 'PBTFans Retro Keycaps', 
     'product_imgs/pbtfans_retro_keycaps.webp', 
     'Photo of Set of Light-Gray, Dark-Gray Keycaps, with a select few being Red, Yellow, and Blue',
     44.99, 'keycaps', 'Keycaps from KBDFans'),
    (8, 'PBTFans Ryokan Keycaps', 
     'product_imgs/pbtfans_ryokan_keycaps.webp',
     'Photo of Set of Light-Brown/Tan Keycaps, with a select few being Darker Shades of Brown',
     44.99, 'keycaps', 'Keycaps from KBDFans'),
    (9, 'Tiger Lite 80% Keyboard Kit with Clear Black Case', 
     'product_imgs/tigerlite_80_clear_black.webp', 
     'Photo of Keyboard with Black Keycaps, and Black-Tinted Translucent Case',
     144.99, '80percent', 'Keyboard Kit by Tiger Lite, 80% layout'),
    (10, 'Tofu Fully-Built 60% Keyboard in Black Case',
     'product_imgs/tofu_60_black.webp', 
     'Photo of Keyboard with Purple Keycaps, and Black Case',
     144.99, '60percent', 
     'Fully Built Tofu Keyboard \n 60% layout \n Black'),
    (11, 'Tofu Fully-Built 60% Keyboard in White Case',
     'product_imgs/tofu_60_white.webp', 
     'Photo of Keyboard with White and Pink Keycaps, and White Case',
     140.99, '60percent', 
     'Fully Built Tofu Keyboard \n 60% layout \n White'),
    (12, 'Tofu Fully-Built 60% Keyboard in Gray Case', 
     'product_imgs/tofu_60_gray.webp', 
     'Photo of Keyboard with Gray Keycaps, and Gray Case',
     140.99, '60percent', 
     'Fully Built Tofu Keyboard \n 60% layout \n Gray'),
    (13, 'Tofu Fully-Built 65% Keyboard with Spark Light Keycaps', 
     'product_imgs/tofu_65_spark_light.webp', 
     'Photo of Keyboard with White and Light-Purple Keycaps, and White Case',
     140.99, '65percent', 
     'Fully Built Tofu Keyboard \n 65% layout \n Spark Light Keycaps'),
    (14, 'Tofu Special Vior Fully-Built 65% Keyboard', 
     'product_imgs/tofu_65_vior.webp', 
     'Photo of Keyboard with White and Dark-Royal-Purple Keycaps, and Dark-Royal-Purple Case',
     140.99, '65percent', 
     'Fully Built Tofu Keyboard \n 65% layout \n Gray'),
    (15, 'Tofu Fully-Built 65% Keyboard with White Case', 
     'product_imgs/tofu_65_white.webp', 
     'Photo of Keyboard with White, Dark-Purple, and Black Keycaps, and White Case',
     169.99, '65percent', 
     'Fully Built Tofu Keyboard \n 65% layout \n White'),
    (16, 'Odin 75 Mechanical Keyboard', 
     'product_imgs/odin_75_black.webp',
     'All Black Keyboard (Black Case, Black Keycaps with White Lettering) on Black Pedestal with Black Background',
     129.99, '75percent', 
     'Fully Built Tofu Keyboard \n 65% layout \n Black Keycaps \n Black Case');

INSERT INTO reviews(rid, pid, rating, title, post_date, review_text, uid)
VALUES
    (1, 16, 4, 'Great Keyboard, Good price', '2023-06-09',
     'This was a great first mechanical keyboard. I got it for my girlfriend in black and she has had it for about 3 months now and loves it. The price was pretty good too. My only complaint was that the shipping times were very long. These ship from the US, so I thought they would arrive within the expected 3-5 days, but it ended up taking a bit longer than that, around 7 days before I recieved the package. So be careful about shipping times if you are ordering in a time crunch.',
     3),
    (2, 16, 5, '1337 Haxor Approved', '2023-06-10',
     'Dude I hacked into the mainframe with this bad boy. I downloaded the backdoor and hit the escape key to get out of their system. It was epic.',
     5),
    (3, 16, 1, 'Not Ogre Friendly', '2023-06-10',
     'These keyboards are waay too small for me large ogre hands. They should really start making these things bigger. Like what does an ogre gotta do to keep up with the internet these days? Would not recommend this keyboard for other ogres.',
     4);